import {
  DietaryTag,
  FoodItem,
  MacroTotals,
  Recipe,
  MealKey,
} from '../types/nutrition';

export const DIETARY_TAGS_META: Array<{ tag: DietaryTag; label: string }> = [
  { tag: 'vegetarian', label: 'Vegetarian' },
  { tag: 'vegan', label: 'Vegan' },
  { tag: 'dairy-free', label: 'Dairy-free' },
  { tag: 'gluten-free', label: 'Gluten-free' },
];

export const RECIPES: Recipe[] = [
  {
    id: 'r-greek-bowl',
    name: 'Greek Yogurt Protein Bowl',
    description: 'Creamy protein + fiber to start your day strong.',
    mealTypes: ['Breakfast'],
    dietaryTags: ['vegetarian', 'gluten-free'],
    items: [
      {
        id: 'f-greek-yogurt',
        name: 'Greek yogurt (1 cup)',
        calories: 150,
        protein: 20,
        carbs: 8,
        fat: 3,
        tags: ['vegetarian', 'gluten-free'],
      },
      {
        id: 'f-gf-granola',
        name: 'Gluten-free granola (1/4 cup)',
        calories: 110,
        protein: 3,
        carbs: 18,
        fat: 4,
        tags: ['vegetarian', 'gluten-free'],
      },
      {
        id: 'f-berries',
        name: 'Mixed berries (1/2 cup)',
        calories: 50,
        protein: 1,
        carbs: 12,
        fat: 0,
        tags: ['vegetarian', 'gluten-free'],
      },
    ],
  },
  {
    id: 'r-overnight-oats',
    name: 'Overnight Oats',
    description: 'Easy prep oats with chia for steady energy.',
    mealTypes: ['Breakfast', 'Snacks'],
    dietaryTags: ['vegetarian', 'gluten-free'],
    items: [
      {
        id: 'f-gf-oats',
        name: 'Gluten-free oats (1/2 cup)',
        calories: 160,
        protein: 6,
        carbs: 28,
        fat: 3,
        tags: ['vegetarian', 'gluten-free'],
      },
      {
        id: 'f-chia',
        name: 'Chia seeds (1 tbsp)',
        calories: 60,
        protein: 3,
        carbs: 5,
        fat: 4,
        tags: ['vegetarian', 'gluten-free'],
      },
      {
        id: 'f-almond-milk',
        name: 'Almond milk (1/2 cup)',
        calories: 30,
        protein: 1,
        carbs: 2,
        fat: 2,
        tags: ['vegetarian', 'gluten-free', 'dairy-free'],
      },
      {
        id: 'f-banana-slices',
        name: 'Banana slices',
        calories: 60,
        protein: 1,
        carbs: 15,
        fat: 0,
        tags: ['vegetarian', 'gluten-free', 'dairy-free'],
      },
    ],
  },
  {
    id: 'r-chicken-rice-bowl',
    name: 'Chicken Rice Bowl',
    description: 'Lean chicken + rice + veggies for a complete meal.',
    mealTypes: ['Lunch', 'Dinner'],
    dietaryTags: ['gluten-free', 'dairy-free'],
    items: [
      {
        id: 'f-chicken',
        name: 'Chicken breast (4 oz)',
        calories: 180,
        protein: 35,
        carbs: 0,
        fat: 3,
        tags: ['gluten-free', 'dairy-free'],
      },
      {
        id: 'f-rice',
        name: 'Rice (1 cup cooked)',
        calories: 205,
        protein: 4,
        carbs: 45,
        fat: 0,
        tags: ['gluten-free', 'dairy-free'],
      },
      {
        id: 'f-veg',
        name: 'Mixed vegetables (1 cup)',
        calories: 70,
        protein: 3,
        carbs: 14,
        fat: 1,
        tags: ['gluten-free', 'dairy-free', 'vegetarian'],
      },
      {
        id: 'f-olive-oil',
        name: 'Olive oil (1 tbsp)',
        calories: 119,
        protein: 0,
        carbs: 0,
        fat: 13,
        tags: ['gluten-free', 'dairy-free', 'vegetarian'],
      },
    ],
  },
  {
    id: 'r-salmon-quinoa',
    name: 'Salmon Quinoa Plate',
    description: 'Omega-3 rich salmon with fluffy quinoa.',
    mealTypes: ['Dinner'],
    dietaryTags: ['gluten-free', 'dairy-free'],
    items: [
      {
        id: 'f-salmon',
        name: 'Salmon (4 oz)',
        calories: 240,
        protein: 25,
        carbs: 0,
        fat: 14,
        tags: ['gluten-free', 'dairy-free'],
      },
      {
        id: 'f-quinoa',
        name: 'Quinoa (1 cup cooked)',
        calories: 222,
        protein: 8,
        carbs: 39,
        fat: 3,
        tags: ['gluten-free', 'dairy-free', 'vegetarian'],
      },
      {
        id: 'f-roasted-veggies',
        name: 'Roasted veggies (1 cup)',
        calories: 80,
        protein: 3,
        carbs: 14,
        fat: 2,
        tags: ['gluten-free', 'dairy-free', 'vegetarian'],
      },
    ],
  },
  {
    id: 'r-turkey-chili',
    name: 'Turkey Chili',
    description: 'Big flavor, high protein, and slow-digesting carbs.',
    mealTypes: ['Lunch', 'Dinner'],
    dietaryTags: ['gluten-free', 'dairy-free'],
    items: [
      {
        id: 'f-turkey',
        name: 'Ground turkey (4 oz)',
        calories: 170,
        protein: 22,
        carbs: 0,
        fat: 8,
        tags: ['gluten-free', 'dairy-free'],
      },
      {
        id: 'f-kidney-beans',
        name: 'Kidney beans (1/2 cup)',
        calories: 130,
        protein: 9,
        carbs: 23,
        fat: 0,
        tags: ['gluten-free', 'dairy-free', 'vegetarian'],
      },
      {
        id: 'f-tomatoes',
        name: 'Crushed tomatoes (1/2 cup)',
        calories: 60,
        protein: 3,
        carbs: 10,
        fat: 1,
        tags: ['gluten-free', 'dairy-free', 'vegetarian'],
      },
      {
        id: 'f-avocado-topping',
        name: 'Avocado (1/4)',
        calories: 80,
        protein: 1,
        carbs: 4,
        fat: 7,
        tags: ['gluten-free', 'dairy-free', 'vegetarian'],
      },
    ],
  },
  {
    id: 'r-tofu-stir-fry',
    name: 'Tofu Stir-fry (GF)',
    description: 'Crispy tofu with vibrant veggies and a savory GF sauce.',
    mealTypes: ['Lunch', 'Dinner'],
    dietaryTags: ['vegan', 'gluten-free', 'dairy-free'],
    items: [
      {
        id: 'f-tofu',
        name: 'Tofu (6 oz)',
        calories: 200,
        protein: 20,
        carbs: 6,
        fat: 12,
        tags: ['vegan', 'gluten-free', 'dairy-free', 'vegetarian'],
      },
      {
        id: 'f-tamari',
        name: 'Tamari (gluten-free soy sauce)',
        calories: 15,
        protein: 1,
        carbs: 1,
        fat: 0,
        tags: ['vegan', 'gluten-free', 'dairy-free', 'vegetarian'],
      },
      {
        id: 'f-veggies',
        name: 'Stir-fry vegetables (2 cups)',
        calories: 120,
        protein: 5,
        carbs: 20,
        fat: 2,
        tags: ['vegan', 'gluten-free', 'dairy-free', 'vegetarian'],
      },
      {
        id: 'f-rice',
        name: 'Rice (1 cup cooked)',
        calories: 205,
        protein: 4,
        carbs: 45,
        fat: 0,
        tags: ['vegan', 'gluten-free', 'dairy-free'],
      },
    ],
  },
  {
    id: 'r-chickpea-quinoa-salad',
    name: 'Chickpea Quinoa Salad',
    description: 'Crunchy, filling, and packed with plant protein.',
    mealTypes: ['Lunch', 'Dinner'],
    dietaryTags: ['vegetarian', 'gluten-free', 'dairy-free'],
    items: [
      {
        id: 'f-quinoa',
        name: 'Quinoa (1 cup cooked)',
        calories: 222,
        protein: 8,
        carbs: 39,
        fat: 3,
        tags: ['vegetarian', 'gluten-free', 'dairy-free'],
      },
      {
        id: 'f-chickpeas',
        name: 'Chickpeas (1 cup)',
        calories: 250,
        protein: 14,
        carbs: 45,
        fat: 4,
        tags: ['vegetarian', 'gluten-free', 'dairy-free', 'vegan'],
      },
      {
        id: 'f-cucumber',
        name: 'Cucumber + tomatoes (1 cup)',
        calories: 60,
        protein: 2,
        carbs: 12,
        fat: 0,
        tags: ['vegetarian', 'gluten-free', 'dairy-free', 'vegan'],
      },
      {
        id: 'f-olive-oil',
        name: 'Olive oil (1 tbsp)',
        calories: 119,
        protein: 0,
        carbs: 0,
        fat: 13,
        tags: ['vegetarian', 'gluten-free', 'dairy-free', 'vegan'],
      },
    ],
  },
  {
    id: 'r-avocado-egg-toast',
    name: 'Egg & Avocado Toast (GF)',
    description: 'Protein + healthy fats for a clean energy boost.',
    mealTypes: ['Breakfast'],
    dietaryTags: ['vegetarian', 'gluten-free'],
    items: [
      {
        id: 'f-eggs',
        name: 'Eggs (2 large)',
        calories: 140,
        protein: 12,
        carbs: 1,
        fat: 10,
        tags: ['vegetarian', 'gluten-free'],
      },
      {
        id: 'f-gf-bread',
        name: 'Gluten-free bread (2 slices)',
        calories: 160,
        protein: 8,
        carbs: 28,
        fat: 2,
        tags: ['vegetarian', 'gluten-free'],
      },
      {
        id: 'f-avocado',
        name: 'Avocado (1/2)',
        calories: 160,
        protein: 3,
        carbs: 8,
        fat: 14,
        tags: ['vegetarian', 'gluten-free', 'dairy-free'],
      },
    ],
  },
  {
    id: 'r-pb-banana-smoothie',
    name: 'PB Banana Protein Smoothie',
    description: 'Sweet, filling, and easy to fit into any day.',
    mealTypes: ['Snacks', 'Breakfast'],
    dietaryTags: ['vegan', 'gluten-free', 'dairy-free'],
    items: [
      {
        id: 'f-banana',
        name: 'Banana',
        calories: 105,
        protein: 1,
        carbs: 27,
        fat: 0,
        tags: ['vegan', 'gluten-free', 'dairy-free'],
      },
      {
        id: 'f-plant-protein',
        name: 'Plant protein powder',
        calories: 120,
        protein: 25,
        carbs: 3,
        fat: 1,
        tags: ['vegan', 'gluten-free', 'dairy-free'],
      },
      {
        id: 'f-peanut-butter',
        name: 'Peanut butter (1 tbsp)',
        calories: 95,
        protein: 4,
        carbs: 3,
        fat: 8,
        tags: ['vegan', 'gluten-free', 'dairy-free'],
      },
      {
        id: 'f-almond-milk',
        name: 'Almond milk',
        calories: 30,
        protein: 1,
        carbs: 2,
        fat: 2,
        tags: ['vegan', 'gluten-free', 'dairy-free'],
      },
    ],
  },
  {
    id: 'r-lentil-soup',
    name: 'Hearty Lentil Soup (Vegan)',
    description: 'Warm comfort with high fiber and steady macros.',
    mealTypes: ['Dinner', 'Lunch'],
    dietaryTags: ['vegan', 'gluten-free', 'dairy-free', 'vegetarian'],
    items: [
      {
        id: 'f-lentils',
        name: 'Lentils (1 cup)',
        calories: 300,
        protein: 22,
        carbs: 50,
        fat: 1,
        tags: ['vegan', 'gluten-free', 'dairy-free', 'vegetarian'],
      },
      {
        id: 'f-veg',
        name: 'Soup vegetables',
        calories: 90,
        protein: 4,
        carbs: 16,
        fat: 1,
        tags: ['vegan', 'gluten-free', 'dairy-free', 'vegetarian'],
      },
      {
        id: 'f-olive-oil',
        name: 'Olive oil (1 tbsp)',
        calories: 119,
        protein: 0,
        carbs: 0,
        fat: 13,
        tags: ['vegan', 'gluten-free', 'dairy-free', 'vegetarian'],
      },
    ],
  },
];

export function calculateTotals(items: FoodItem[]): MacroTotals {
  return items.reduce(
    (totals, item) => {
      totals.calories += item.calories;
      totals.protein += item.protein;
      totals.carbs += item.carbs;
      totals.fat += item.fat;
      return totals;
    },
    { calories: 0, protein: 0, carbs: 0, fat: 0 } satisfies MacroTotals
  );
}

export function getRecipeTotals(recipe: Recipe): MacroTotals {
  return calculateTotals(recipe.items);
}

export function getRecipesForMealType(recipes: Recipe[], mealType: MealKey) {
  return recipes.filter((r) => r.mealTypes.includes(mealType));
}

